auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

memberlist:
  join_members: ["loki"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 10s
  bind_addr: ["0.0.0.0"]
  bind_port: 7946
  advertise_addr: 127.0.0.1
  gossip_interval: 2s

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  chunk_idle_period: 15s
  chunk_retain_period: 5s
  max_chunk_age: 30s
  chunk_target_size: 524288
  flush_check_period: 5s

limits_config:
  discover_log_levels: true
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://loki:3100
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: loki1234
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

ruler:
  storage:
    s3:
      bucketnames: loki-ruler
