apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    version: 1
    uid: loki
    jsonData:
      derivedFields:
        - name: "trace_id"
          matcherType: "label"
          matcherRegex: trace_id
          url: "$${__value.raw}"
          urlDisplayLabel: "traces"
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: false
    version: 1
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags: [{ key: "service.name", value: "service_name" }]
        filterByTraceId: false
        filterBySpanId: false
        customQuery: true
        query: '{$${__tags}} | trace_id="$${__span.traceId}"'

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false
    editable: false
    version: 1
    uid: mimir

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    version: 1
    uid: prometheus
